# Regime settings
DEFAULT_PERIOD = 14
CHOP_TRENDING_THRESHOLD = 38
MIN_CANDLES_TREND = 20
MIN_CANDLES_VOLATILITY = 50
VOLATILITY_HIGH_RATIO = 1.5
VOLATILITY_LOW_RATIO = 0.7
# Future: volatility_threshold, chop_index_limit
